name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:

env:
  # Must exist in repo secrets
  # ACR_LOGIN_SERVER = acrmitalikaurweek07.azurecr.io
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Quick guard so we fail early if the secret is missing
      - name: Sanity check env
        run: |
          echo "Registry: ${{ env.ACR_LOGIN_SERVER }}"
          test -n "${{ env.ACR_LOGIN_SERVER }}"

      # Login directly to ACR with admin credentials (same as backend)
      - name: Docker login to ACR
        run: |
          echo "${{ secrets.ACRPASSWORD }}" | docker login "${{ env.ACR_LOGIN_SERVER }}" \
            --username "${{ secrets.ACRUSERNAME }}" --password-stdin

      # Build & push the frontend image (adjust path/tag if you use a different name)
      - name: Build and Push Frontend Image
        run: |
          docker build -t "${{ env.ACR_LOGIN_SERVER }}/frontend:latest" ./frontend
          docker push "${{ env.ACR_LOGIN_SERVER }}/frontend:latest"
